version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      commit_message:
        prefix: "chore(deps)"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      commit_message:
        prefix: "chore(deps)"
