/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package anupam.acrylic;

public final class R {
  public static final class dimen {
    public static final int activity_horizontal_margin=0x7f010000;
    public static final int activity_vertical_margin=0x7f010001;
  }
  public static final class drawable {
    public static final int about=0x7f020000;
    public static final int actionbar_background=0x7f020001;
    public static final int blur=0x7f020002;
    public static final int clear_all=0x7f020003;
    public static final int color=0x7f020004;
    public static final int emboss=0x7f020005;
    public static final int erase=0x7f020006;
    public static final int extract_color=0x7f020007;
    public static final int fill_background_with_color=0x7f020008;
    public static final int ic_launcher=0x7f020009;
    public static final int import_image=0x7f02000a;
    public static final int save=0x7f02000b;
    public static final int share=0x7f02000c;
    public static final int size=0x7f02000d;
    public static final int smudge=0x7f02000e;
    public static final int splash=0x7f02000f;
  }
  public static final class id {
    public static final int CanvasId=0x7f030000;
    public static final int aboutTextView=0x7f030001;
    public static final int about_menu=0x7f030002;
    public static final int blur_menu=0x7f030003;
    public static final int brushSizeSeekBar=0x7f030004;
    public static final int clear_all_menu=0x7f030005;
    public static final int color_menu=0x7f030006;
    public static final int emboss_menu=0x7f030007;
    public static final int erase_menu=0x7f030008;
    public static final int extract_color_menu=0x7f030009;
    public static final int fill_background_with_color=0x7f03000a;
    public static final int normal_brush_menu=0x7f03000b;
    public static final int open_image_menu=0x7f03000c;
    public static final int root=0x7f03000d;
    public static final int save_menu=0x7f03000e;
    public static final int share_menu=0x7f03000f;
    public static final int sizeValueTextView=0x7f030010;
    public static final int size_menu=0x7f030011;
    public static final int smudge_menu=0x7f030012;
  }
  public static final class layout {
    public static final int activity_about=0x7f040000;
    public static final int brush=0x7f040001;
    public static final int main=0x7f040002;
  }
  public static final class menu {
    public static final int main=0x7f050000;
  }
  public static final class string {
    public static final int ability_disabled_need_newer_api_level=0x7f060000;
    public static final int about=0x7f060001;
    public static final int about_description=0x7f060002;
    public static final int app_description=0x7f060003;
    public static final int app_name=0x7f060004;
    public static final int blur=0x7f060005;
    public static final int brush_size=0x7f060006;
    public static final int choose_width=0x7f060007;
    public static final int clear_all=0x7f060008;
    public static final int color=0x7f060009;
    public static final int color_extracted=0x7f06000a;
    public static final int continue_fuck=0x7f06000b;
    public static final int emboss=0x7f06000c;
    public static final int erase=0x7f06000d;
    public static final int extract_color=0x7f06000e;
    public static final int fill_background_with_color=0x7f06000f;
    public static final int here_is_your_canvas=0x7f060010;
    public static final int no_way_to_share=0x7f060011;
    public static final int normal=0x7f060012;
    public static final int ok=0x7f060013;
    public static final int open_image=0x7f060014;
    public static final int pick_color=0x7f060015;
    public static final int press_back_again=0x7f060016;
    public static final int save=0x7f060017;
    public static final int saved_your_location_to=0x7f060018;
    public static final int select=0x7f060019;
    public static final int select_image_to_open=0x7f06001a;
    public static final int share=0x7f06001b;
    public static final int share_text_template=0x7f06001c;
    public static final int share_title_template=0x7f06001d;
    public static final int smudge=0x7f06001e;
    public static final int tap_to_extract_color=0x7f06001f;
    public static final int title_activity_about=0x7f060020;
    public static final int toolbox_share_title=0x7f060021;
    public static final int your_selected_size_is=0x7f060022;
  }
  public static final class style {
    public static final int MyActionBar=0x7f070000;
    public static final int Theme=0x7f070001;
  }
}