name: Setup test environment

runs:
  using: "composite"
  steps:
    - name: Set git user
      shell: bash
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "<>"
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@da36cb69b1c3247ad7a1f931ebfd954a1105ef14 # v14
    - uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b # v8
    - name: Check Nixpkgs inputs
      uses: DeterminateSystems/flake-checker-action@078f5f7f47ee188aa6cb472527ca5984e195222d # v9
      with:
        fail-mode: true
    - name: Use Maven dependency cache
      uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4.1.1
      with:
        path: ~/.m2/repository
        # We use a unique key and restore from the base one, to ensure that
        # the cache is updated every time, even if a cache hit was observed.
        # See
        # https://github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache
        # for more information.
        key: ${{ runner.os }}-maven-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-maven
