name: Setup test environment

runs:
  using: "composite"
  steps:
    - name: Set git user
      shell: bash
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "<>"
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@21a544727d0c62386e78b4befe52d19ad12692e3 # v17
    - uses: DeterminateSystems/magic-nix-cache-action@6221693898146dc97e38ad0e013488a16477a4c4 # v9
    - name: Check Nixpkgs inputs
      uses: DeterminateSystems/flake-checker-action@078f5f7f47ee188aa6cb472527ca5984e195222d # v9
      with:
        fail-mode: true
    - name: Use Maven dependency cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ~/.m2/repository
        # We use a unique key and restore from the base one, to ensure that
        # the cache is updated every time, even if a cache hit was observed.
        # See
        # https://github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache
        # for more information.
        key: ${{ runner.os }}-maven-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-maven
