name: Setup test environment

runs:
  using: "composite"
  steps:
    - name: Set git user
      shell: bash
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "<>"
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21
    - uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13
    - name: Check Nixpkgs inputs
      uses: DeterminateSystems/flake-checker-action@3164002371bc90729c68af0e24d5aacf20d7c9f6 # v12
      with:
        fail-mode: false
    - name: Use Maven dependency cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ~/.m2/repository
        # We use a unique key and restore from the base one, to ensure that
        # the cache is updated every time, even if a cache hit was observed.
        # See
        # https://github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache
        # for more information.
        key: ${{ runner.os }}-maven-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-maven
