name: dirty-waters

on:
  pull_request:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      ignore_cache:
        description: "Ignore the repository cache for this run"
        required: false
        default: "false"

jobs:
  dirty-waters:
    runs-on:
        ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup JDK17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Dirty Waters Analysis
        uses: chains-project/dirty-waters-action@b88cb4e69c6007cab8cafdcdaf815c3d66daa0f4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_manager: maven
          #no_gradual_report: true
