name: Dirty Waters Analysis

on:
  pull_request:
    paths:
      - "**/package.json"
      - "**/package-lock.json"
      - "**/yarn.lock"
      - "**/pnpm-lock.yaml"
      - "**/pom.xml"
  push:
    branches:
      - main
      - master
      #paths:
      #- "**/package.json"
      #- "**/package-lock.json"
      #- "**/yarn.lock"
      #- "**/pnpm-lock.yaml"
      #- "**/pom.xml"

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Dirty Waters database
        uses: actions/cache@v4
        with:
          path: tool/cache
          key: ${{ runner.os }}-dirty-waters-cache-${{ github.repository }}
          restore-keys: |
            ${{ runner.os }}-dirty-waters-cache-

      - name: Check if first dirty-waters run
        id: check-first-run
        run: |
          WORKFLOW_FILE=$(gh api repos/${{ github.repository }}/actions/workflows --jq '.workflows[] | select(.name == "${{ github.workflow }}") | .path' | xargs basename)
          RUNS=$(gh api repos/${{ github.repository }}/actions/workflows/$WORKFLOW_FILE/runs --jq '[.workflow_runs[] | select(.conclusion=="success")] | length')
          echo "is_first_run=$([[ $RUNS -le 1 ]] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash

      - name: Run Static Dirty Waters analysis
        if: steps.check-first-run.outputs.is_first_run == 'true'
        uses: chains-project/dirty-waters-action@70d5044612d1c4360f9588ae902a1962ad2aa7dd
        with:
          # example args, change as needed
          dirty_waters_version: 3b83ec05b4072e43e65a2ad95b33d9523e0dbda3
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_repo: ${{ github.repository }}
          differential_analysis: false
          package_manager: maven # Change this according to your project
          comment_on_commit: true # Optional: comments on commits (outside PRs) if high severity issues are found

      - name: Run Differential Dirty Waters Analysis
        if: ${{ !(steps.check-first-run.outputs.is_first_run == 'true') }}
        uses: chains-project/dirty-waters-action@70d5044612d1c4360f9588ae902a1962ad2aa7dd
        with:
          # example args, change as needed
          dirty_waters_version: 3b83ec05b4072e43e65a2ad95b33d9523e0dbda3
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_repo: ${{ github.repository }}
          package_manager: maven # Change this according to your project
          comment_on_commit: true # Optional: comments on commits (outside PRs) if high severity issues are found
