name: dirty-waters

on:
  pull_request:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      ignore_cache:
        description: "Ignore the repository cache for this run"
        required: false
        default: "false"

jobs:
  dirty-waters:
    runs-on:
        ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup JDK17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Dirty Waters Analysis
        uses: chains-project/dirty-waters-action@f5762601b3d8831bb9d64ba0d9cd45b75e531914
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_manager: maven
          gradual_report: false
          debug: true
          comment_on_commit: true
