name: Docker
on:
  push:
    branches:
      - *
jobs:
  check-lockfile:
        runs-on: ubuntu-latest
        needs: build-and-publish
        steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'temurin'
        - name: run maven-lockfile
          uses: chains-project/maven-lockfile@main
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
