name: LSIF
on:
  push:
    branches: 
      - master
jobs:
  build:
    name: Build and push LSIF data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate LSIF data
        uses: sourcegraph/lsif-java-action@2de844423a3d94075b845b9d18b30b883b8b967c
        with:
          verbose: true
      - name: Upload LSIF data
        uses: sourcegraph/lsif-upload-action@master
        with:
          endpoint: https://sourcegraph.com
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file: dump.lsif
          ignore_upload_failure: true
