# Workflow for testing spoon code quality.
#
# Note that actions are specified by commit hash. This is to avoid the security
# risk of someone injecting malicious code into a release and then simply
# changing a tag.

name: Qodana
on:
  pull_request:
    branches:
      - master
jobs:
    code-quality:
      runs-on: ubuntu-latest
      name: code-quality qodana
      steps:
        - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
          with:
            fetch-depth: 0
        - name: 'Qodana Scan'
          uses: JetBrains/qodana-action@d7b5ec2fbec32197ef447c450e00589ed5f34fd5 # v2026.1.0
          with:
            args: --source-directory,./src/main/java , --fail-threshold, 0
            post-pr-comment: "false"
        - uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4
          with:
            sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
    code-quality-spoon-javadoc:
      runs-on: ubuntu-latest
      name: code-quality spoon-javadoc qodana
      steps:
        - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
          with:
            fetch-depth: 0
        - name: 'Qodana Scan (spoon-javadoc)'
          uses: JetBrains/qodana-action@d7b5ec2fbec32197ef447c450e00589ed5f34fd5 # v2026.1.0
          with:
            args: --source-directory,./spoon-javadoc/src/main/java , --fail-threshold, 0
            post-pr-comment: "false"
        - uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4
          with:
            sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
    code-quality-spoon-control-flow:
      runs-on: ubuntu-latest
      name: code-quality spoon-controlflow qodana
      steps:
        - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
          with:
            fetch-depth: 0
        - name: 'Qodana Scan (spoon-control-flow)'
          uses: JetBrains/qodana-action@d7b5ec2fbec32197ef447c450e00589ed5f34fd5 # v2026.1.0
          with:
            args: --source-directory,./spoon-control-flow/src/main/java , --fail-threshold, 0
            post-pr-comment: "false"
        - uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4
          with:
            sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
