name: Release nightly version

on:
    schedule:
      - cron: '0 0 * * *' # Every day at 00:00 UTC (https://crontab.guru/#0_0_*_*_*)
    # For testing also allow it now...
    pull_request:
      branches:
        - master

jobs:
  nightly:
    uses: ./.github/workflows/jreleaser.yml
    with:
      release-script-to-run: chore/release-nightly.sh
      attest-artifacts: true
    secrets: inherit
