name: Release beta version

on:
    schedule:
      - cron: '0 0 * * 0' # Sundays at 00:00 (https://crontab.guru/#0_0_*_*_0)

jobs:
  snapshot:
    uses: ./.github/workflows/jreleaser.yml
    with:
      release-script-to-run: chore/release-beta.sh
    secrets: inherit
